### PR TITLE
fix: check for editor in environment variables

### LINKED ISSUE #745: Unable to send pull requests (and peerDependencies errors)
**Version number**
2.8.1

**Describe the bug**

After installing the package via 

`npm i -g gh`

A warning is shown

```
npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.
```

When trying to run `gh pr -s SOME_GITHUB_USERNAME` an error is thrown

```
Submitting pull request to SOME_GITHUB_USERNAME
/bin/sh: 1: /tmp/tmp-29718S1GXHRWm3gvv-temp-gh-pr-title.txt: Permission denied
fatal: Could not use your editor to store a custom message
 { Error: Command failed:  "/tmp/tmp-29718S1GXHRWm3gvv-temp-gh-pr-title.txt"
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.execSyncInteractiveStream (/usr/lib/node_modules/gh/lib/exec.js:58:25)
    at Object.openFileInEditor (/usr/lib/node_modules/gh/lib/utils.js:74:16)
    at submit (/usr/lib/node_modules/gh/lib/cmds/pull-request/submit.js:22:25)
    at Object.submitHandler (/usr/lib/node_modules/gh/lib/cmds/pull-request/submit.js:50:26)
  status: 126,
  signal: null,
  output: [ null, null, null ],
  pid: 29755,
  stdout: null,
  stderr: null }
```

(Obviously SOME_GITHUB_USERNAME is a real username on GitHub, I just didn't want to include it in the bug report for privacy reasons.)

**To Reproduce**

Please see description above

**Expected behavior**

I expect this package to work as intended, `gh pr -s SOME_GITHUB_USERNAME` should submit the pull request to SOME_GITHUB_USERNAME on Github.

**Screenshots**

image

**Additional context**

- node version: v10.16.3
- npm version: 6.9.0
- Also tried with yarn v1.19.1
- With previous versions (and on the same hardware) this was working fine.

### PR DESCRIPTION
**Pull request by julien**
To determine which editor to use for commit messages
look if $EDITOR or $VISUAL are set in the environment
before checking the git config. If no editor is found
throw an error. Fixes #745

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -77,7 +77,15 @@ export function openFileInEditor(fileName: string, msg: string): string {
 
         writeFileSync(filePath, msg)
 
-        const editor = spawnSync('git', ['config', '--global', 'core.editor']).stdout
+        const editor = process.env.EDITOR
+            ? process.env.EDITOR
+            : process.env.VISUAL
+            ? process.env.VISUAL
+            : spawnSync('git', ['config', '--global', 'core.editor']).stdout
+
```
Comment (protoEvangelion) [inline src/utils.ts]: Is your logic trying to say, use `EDITOR`, if that's not there fallback to `VISUAL`, if that's not there get it from git?

If so can we clean it up like:

```javascript
const editor = process.env.EDITOR || process.env.VISUAL || spawnSync('git', ['config', '--global', 'core.editor']).stdout
```

**Comment by protoEvangelion** [comment]
Just started reviewing :)

**Comment by protoEvangelion** [comment]
Hmm it's passing locally but not on CI. I'm looking into it now.

File: src/utils.ts (hunk 1 above)
Comment (julien) [reply src/utils.ts]: @protoEvangelion sorry for the late reply, time zone differences are hard to deal with.

I'm going to change this as you suggested, as for the failing test, I'm guessing it's because I'm throwing an error.
I'll push my changes and see what happens - locally no tests fail.

Comment (protoEvangelion) [reply src/utils.ts]: Thanks for the quick turnaround on this! I'm updating the docs & then I will merge this.

Comment (julien) [reply src/utils.ts]: Thanks to you, no worries on my side it was fun contributing to a project I use daily at work

Comment (protoEvangelion) [reply src/utils.ts]: Awesome, let me know if you have more ideas. I'm happy to chat 👍
